page_title                                : Go Buddy Hearts

# App Info
ios_app_id                                : 6740586597                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/app-icon.png                       # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Best Friends Faster

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Katrina Owen
your_link                                 : https://exercism.github.io/kytrinyx/
your_city                                 : Norway
email_address                             : kytrinyx@gmail.com
facebook_username                         :
instagram_username                        :
twitter_username                          :
github_username                           : kytrinyx
youtube_username                          :
mastodon_link                             :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Emotional Points Tracker
    description                           : Easily keep track of exactly how many emotional points your buddy has gained... or lost.
    fontawesome_icon_name                 : calculator

  - title                                 : Decay Timer
    description                           : Make sure that you interact with your buddy again, before losing points to inactivity.
    fontawesome_icon_name                 : stopwatch

  - title                                 : Cooldown Timers
    description                           : See at a glance which actions are available, and how long you have to wait before doing a given action again.
    fontawesome_icon_name                 : hourglass-half

  - title                                 : Detailed History
    description                           : Get an overview over exactly how the different interactions, refreshes, decays, and undos contributed to the current score.
    fontawesome_icon_name                 : list

  - title                                 : Undo
    description                           : Accidentally clicked the wrong action? No problem. Undo that action, and click the right one.
    fontawesome_icon_name                 : undo

  - title                                 : Emotion Points Breakdown
    description                           : Understand how the buddy mood algorithm works.
    fontawesome_icon_name                 : question-circle



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
